---
name: Omada Controller
version: 0.1.0
slug: omada
description: Manage your TP-Link Omada hardware
url: https://github.com/reey/addon-omada
webui: https://[HOST]:[PORT:8043]
watchdog: https://[HOST]:[PORT:8043]/login
startup: services
arch:
  - aarch64
  - amd64
init: false
backup: cold
map:
  - ssl
options:
  certfile: fullchain.pem
  keyfile: privkey.pem
  memory_max: 1024
  memory_init: 128
  serverLogs: false
  mongoLogs: false
schema:
  memory_max: int?
  memory_init: int?
  certfile: str
  keyfile: str
  serverLogs: bool?
  mongoLogs: bool?
host_network: true
ports:
  8088/tcp: 8088
  8043/tcp: 8043
  8843/tcp: 8843
  29810/udp: 29810
  29811/tcp: 29811
  29812/tcp: 29812
  29813/tcp: 29813
  29814/tcp: 29814
ports_description:
  8088/tcp: Management portal HTTP
  8043/tcp: Management portal HTTPS
  8843/tcp: User portal HTTPS
  29810/udp: Discover Omada devices
  29811/tcp: Adopt & Manage Omada devices <=v4.x
  29812/tcp: Adopt & Manage Omada devices <=v4.x
  29813/tcp: Upgrade Omada devices
  29814/tcp: Adopt & Manage Omada devices >=v5.x
hassio_api: true
